# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# pool:
#   vmImage: ubuntu-latest
pool: default


steps:
- script: echo Hello, world!
  displayName: 'chumascalo adrian'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'csantiagos'
    scannerMode: 'MSBuild'
    projectKey: '13d95e66f41a6e9e451271fde4a4f9a67f8f363a'
    projectName: 'csantiagos'

- task: SonarCloudAnalyze@1